<?php

namespace BanqueBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
