version: '2'

services:

  app_intra:
    build: docker
    container_name: app_intra
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html"
    links:
      - db_intra:db
      - phpmyadmin_intra:phpmyadmin
    environment:
      TYPE_ENVIRONNEMENT: dev

  db_intra:
      image: mysql:5.5
      container_name: db_intra
      ports:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: "intra"
        MYSQL_USER: "intra"
        MYSQL_PASSWORD: "intra"
        MYSQL_DATABASE: "intra"

  phpmyadmin_intra:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin_intra
      environment:
        - "PMA_ARBITRARY=1"
        - "PMA_HOST=db"
        - "PMA_USER=root"
        - "PMA_PASSWORD=intra"
      restart: always
      ports:
        - 8083:80
      links:
        - db_intra:db

