parameters:

services:
    app.user.provider.fosuser:
        class : UserBundle\Security\Core\UserProvider
        arguments:
           - "@fos_user.user_manager"
           - { facebook: facebookID }
